// api/privacy.js
// Privacy Policy page for unfindable.ai
// Hosted at /api/privacy — use this URL in Meta App Settings

export default function handler(req, res) {
  res.setHeader("Content-Type", "text/html");
  res.status(200).send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Privacy Policy — unfindable.ai</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      background: #0a0a0a;
      color: #c8c8c8;
      font-family: 'Georgia', serif;
      line-height: 1.8;
      padding: 60px 24px;
    }

    .container {
      max-width: 680px;
      margin: 0 auto;
    }

    .logo {
      font-family: 'Georgia', serif;
      font-size: 13px;
      letter-spacing: 0.3em;
      text-transform: uppercase;
      color: #555;
      margin-bottom: 60px;
    }

    h1 {
      font-size: 28px;
      font-weight: normal;
      color: #f0f0f0;
      margin-bottom: 8px;
      letter-spacing: -0.02em;
    }

    .date {
      font-size: 13px;
      color: #444;
      margin-bottom: 48px;
      letter-spacing: 0.05em;
    }

    h2 {
      font-size: 13px;
      letter-spacing: 0.2em;
      text-transform: uppercase;
      color: #888;
      margin-top: 40px;
      margin-bottom: 12px;
      font-weight: normal;
    }

    p {
      font-size: 15px;
      color: #999;
      margin-bottom: 16px;
    }

    .disclaimer {
      margin-top: 60px;
      padding-top: 32px;
      border-top: 1px solid #1a1a1a;
      font-size: 12px;
      color: #444;
      letter-spacing: 0.03em;
    }

    a {
      color: #666;
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="container">

    <div class="logo">unfindable.ai</div>

    <h1>Privacy Policy</h1>
    <p class="date">Effective date: March 2026</p>

    <p>unfindable.ai ("we", "our", or "the Service") is a personal transformation coaching service delivered via Instagram Direct Messages and powered by artificial intelligence. This Privacy Policy explains what data we collect, how we use it, and your rights.</p>

    <h2>1. What We Collect</h2>
    <p>When you interact with unfindable.ai via Instagram DM, we collect the following information you voluntarily provide:</p>
    <p>Your Instagram user ID (provided automatically by Meta's API); messages you send to the service; personal information you share during onboarding, including birth date, city of residence, profession, and fitness level; activity logs and progress updates you share during coaching sessions.</p>
    <p>We do not collect your full name, email address, phone number, or any financial information.</p>

    <h2>2. How We Use Your Data</h2>
    <p>We use the information you provide solely to deliver and improve your personalised coaching experience. Specifically, we use it to generate daily recommendations tailored to your astrological profile, location, profession, and physical goals; to maintain conversation history so the coaching remains contextual and continuous; and to track your progress streak and protocol day.</p>
    <p>We do not sell your data. We do not use your data for advertising. We do not share your data with third parties except as described in Section 4.</p>

    <h2>3. Data Storage</h2>
    <p>Your profile and conversation history are stored securely in Vercel KV, a managed key-value database. Data is stored under an anonymised key derived from your Instagram user ID. Conversation history is limited to a rolling window of your most recent interactions.</p>

    <h2>4. Third-Party Services</h2>
    <p>unfindable.ai uses the following third-party services to operate:</p>
    <p><strong style="color:#777">Meta (Instagram)</strong> — to receive and send Direct Messages via the Instagram Messaging API. Your use of Instagram is governed by Meta's own Privacy Policy at meta.com/privacy.</p>
    <p><strong style="color:#777">Google Gemini API</strong> — to generate AI coaching responses. Messages are processed by Google's API in accordance with Google's data processing terms.</p>
    <p><strong style="color:#777">Open-Meteo</strong> — to retrieve current weather data for your city. Only your city name is sent; no personal identifiers are transmitted.</p>
    <p><strong style="color:#777">Vercel</strong> — for hosting and data storage. Vercel's infrastructure is SOC 2 compliant.</p>

    <h2>5. AI Disclosure</h2>
    <p>unfindable.ai is an agentic AI service. All coaching responses are generated by artificial intelligence, not by a human coach. In accordance with the EU AI Act (2026) and applicable US state AI disclosure laws including Colorado SB 205 and Texas HB 2060, we disclose that you are interacting with an automated AI system.</p>
    <p>unfindable.ai provides wellness guidance and personal development coaching only. It is not a substitute for licensed clinical therapy, psychiatric care, or medical advice.</p>

    <h2>6. Safety & Crisis Situations</h2>
    <p>If you share content that indicates you may be in crisis or at risk of harm, unfindable.ai is designed to pause its standard coaching flow and provide emergency resource information. We may retain a safety flag on your profile to handle subsequent interactions appropriately. We do not report to authorities based on message content.</p>

    <h2>7. Data Retention & Deletion</h2>
    <p>Your profile and chat history are retained for as long as you actively use the service. You may request deletion of all your data at any time by sending the message "DELETE MY DATA" in a DM to the service. We will permanently delete your profile and conversation history within 7 days of your request.</p>

    <h2>8. Children's Privacy</h2>
    <p>unfindable.ai is intended for users aged 18 and older. We do not knowingly collect data from minors. If you believe a minor has interacted with this service, please contact us immediately.</p>

    <h2>9. Your Rights</h2>
    <p>Depending on your jurisdiction, you may have the right to access the personal data we hold about you; request correction of inaccurate data; request deletion of your data; object to or restrict processing of your data; and lodge a complaint with a supervisory authority (EU users: your national data protection authority).</p>
    <p>To exercise any of these rights, contact us at the address below.</p>

    <h2>10. Changes to This Policy</h2>
    <p>We may update this Privacy Policy from time to time. The effective date at the top of this page will reflect the most recent revision. Continued use of the service after any changes constitutes acceptance of the updated policy.</p>

    <h2>11. Contact</h2>
    <p>For privacy-related questions or data deletion requests, contact us at:<br/>
    <a href="mailto:privacy@unfindable.ai">privacy@unfindable.ai</a></p>

    <div class="disclaimer">
      Consultations by unfindable.ai (Agentic AI System). For wellness guidance only; not a substitute for clinical therapy, psychiatric care, or medical advice. EU AI Act 2026 compliant.
    </div>

  </div>
</body>
</html>`);
}
